### ISSUE TITLE
As a learner, I want to create an account

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/lms#51]
- [x] Decide if I want in app registration or Auth0 sign up
- [x] Personalize Auth0 signup page
- [x] Enforce confirm for emails
- [x] Check that user is real
- [x] Remove the login page

![Image](https://github.com/brooks-builds/lms/assets/8014396/7230f85f-797c-43e9-9858-56aa064de366)

![Image](https://github.com/brooks-builds/lms/assets/8014396/3f9e7d1b-cc63-4f41-bb2d-09c58ccc1bfb)

I don't know why you have 2 but since you have to login using Auth0 anyways maybe it makes more sense to get rid of the onsite sign up? Also the Auth0 login obviously needs some customization. And maybe a confirmation email to make sure the user actually owns the email he is using to make sure no one can create unlimited accounts and mess with your site? For instance an attacker could increase your storage quota with an automated script that creates new useless accounts non-stop. An checkbox to make sure the user is not a robot would also help. In either case you can also protect from this kind of attack if you put a limit on the amount of requests someone can make to your website per IP address per minute.
